version: "3"

services:

  gis_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "apt update &&
             apt install gdal-bin libpq5 -y &&
             python manage.py wait_for_db &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./:/app
    ports:
      - "8888:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3
    ports:
      - "5432:5432"
    volumes:
      - C:/Program\ Files/PostgreSQL/15/data:/var/lib/postgresql
    env_file:
      - .env
